# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin Jaffre - Portefolio
description: Bienvenue sur mon portefolio, je regroupe sur cette page l'ensemble des projets sur lesquels j'ai travaillé (développement comme design) donc n'hésitez pas à y jeter un coup d'œil.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github: kevinjaffre
mail: kevin56620@gmail.com
behance: kevinjaffre

# Build settings
markdown: kramdown
host: 0.0.0.0

# collections
collections:
  projects:
   output: true
   permalink: /project/:path/
